### ISSUE TITLE
Daleran Crater: Bug

### ISSUE THREAD

**Issue by birdboy12** [piehead/TrinityCore#20]
The Mystic Shield that surrounds Daleran Crater does not block character movement into or out of the crater as would be normal.

**Comment by birdboy12** [comment]
![image](https://user-images.githubusercontent.com/52128140/60386148-66df6d80-9a5f-11e9-81e1-779ba3da8568.png)

**Comment by Variona** [comment]
Not a bug. Dalaran was teleported to Northrend in Wrath of the Lich King.
